In [3]:
import pandas as pd 
import os
import platform
import sqlite3

In [4]:
if "pop-os" in platform.node():
    ROOT = r"/home/abishekthamma/PycharmProjects/masters_thesis/ss-llm/nanoGPT/"
else:
    ROOT = r'/gpfs/home4/athamma/repo/ss-llm/nanoGPT/'
    
TOKENIZER_ROOT = os.path.join(ROOT, "data")
OUT_ROOT = os.path.join(ROOT, "output_dump")
RESULTS_ROOT = os.path.join(ROOT, "results")

SQL_DB = os.path.join(RESULTS_ROOT, "results.db")


def create_connection_cursor(db_file):
    """
    Create a database connection to the SQLite database specified by the db_file

    Args:
        db_file (str): database file

    Returns:
        Connection object or None
    """
    conn = sqlite3.connect(db_file)
    c = conn.cursor()
    return conn, c

conn, c = create_connection_cursor(SQL_DB)

In [5]:
words_df = pd.read_sql_query("SELECT * FROM WordDetails", conn)
words_df

,WordUID,Word,CharacterLength,LogFrequencies,QuintilesA1,QuintilesA2
0,1,if,2,5.256744,4,4
1,2,you,3,6.329340,4,4
2,3,were,4,4.928421,4,4
3,4,to,2,6.063172,4,4
4,5,journey,7,3.007748,3,3
...,...,...,...,...,...,...
10134,10135,disks,5,1.913814,2,1
10135,10136,stored,6,2.230449,2,2
10136,10137,embrace,7,2.587711,3,2
10137,10138,coincides,9,1.146128,1,0
10138,10139,604m,4,0.000000,0,-1

In [ ]:
#Create Quintiles (q=5) based on LogFrequencies column

#Note: Issues with this approach is that the log frequencies are derived from (<Fill in>) and so has a many words that are not there in the distribution, which are then assigned 0 by default. For example numbers like 8, 1000 etc. So, all of these get assigned to the lowest quintile. 

# Alternate approach is to tag values that have 0 Logfrequencies and skip those to assign quintiles and use only the non zero values to create quintiles and also use in subsequent analysis.

#Approach 1
words_df['LogFrequencies'] = words_df['LogFrequencies'].astype(float)
words_df['quintiles_a1'] = pd.qcut(words_df['LogFrequencies'], 5, labels=False)
words_df['quintiles_a1'] = words_df['quintiles_a1'].astype(int)
#Approach 2

words_df = words_df.merge(words_df[words_df['LogFrequencies'] > 0][["WordUID", "LogFrequencies"]].copy().assign(quintiles_a2 = lambda x: pd.qcut(x['LogFrequencies'], 5, labels=False)).drop(columns=['LogFrequencies']), on='WordUID', how='left')

words_df['quintiles_a2'] = words_df['quintiles_a2'].fillna(-1).astype(int)


words_df

In [ ]:
#Column datatypes
words_df.dtypes

In [ ]:
# # #Write back quintiles_a1 and quintiles_a2 to the database

# for row in words_df[['WordUID', 'quintiles_a1', 'quintiles_a2']].to_dict(orient='records'):
#     c.execute("UPDATE WordDetails SET QuintilesA1 = ?, QuintilesA2 = ? WHERE WordUID = ?", (row['quintiles_a1'], row['quintiles_a2'], row['WordUID']))
# conn.commit()

In [ ]:
#Alternative Approach - 
# Use spacy's en_core_web_lg model to calculate get token.probs and use that to calculate the quintiles.

words_df

In [1]:
import spacy
from spacy.lookups import load_lookups

nlp = spacy.load("en_core_web_sm")


# Load the probability table from spacy-lookups-data
lookups = load_lookups("en", tables=["lexeme_prob"])
# Add the probability table to the model’s vocab
nlp.vocab.lookups.add_table("lexeme_prob", lookups.get_table("lexeme_prob"))

Table([(12646065887601541794, -3.0678977966),
       (2593208677638477497, -3.454959631),
       (7425985699627899538, -3.5287666321),
       (4690420944186131903, -3.7915651798),
       (3791531372978436496, -3.8560216427),
       (11901859001352538922, -3.9297883511),
       (2283656566040971221, -4.1131081581),
       (886050111519832510, -4.275873661),
       (7624161793554793053, -4.3737912178),
       (10239237003504588839, -4.3880500793),
       (3411606890003347522, -4.4577488899),
       (4380130941430378203, -4.4645047188),
       (908432558851201422, -4.6065607071),
       (3002984154512732771, -4.6190719604),
       (16428057658620181782, -4.8305592537),
       (2043519015752540944, -4.8599386214999996),
       (16037325823156266367, -4.8801093102),
       (15884554869126768810, -5.0267758369),
       (8205403955989537350, -5.0592465401),
       (8532415787641010193, -5.1291651726),
       (14692702688101715474, -5.1564846039),
       (5640369432778651323, -5.1727361679),
       (2005922715127769938, -5.1977410316),
       (3842344029291005339, -5.1979942322),
       (10382539506755952630, -5.2250943184),
       (12510949447758279278, -5.2432498932),
       (2158845516055552166, -5.2469968796),
       (9921686513378912864, -5.2523202896),
       (5012629990875267006, -5.2710680962),
       (447765159362469301, -5.3326010704),
       (14560795576765492085, -5.3419694901),
       (17494803046312582752, -5.3596410751),
       (1995909169258310477, -5.3618164062),
       (4398759943034541363, -5.4381122589),
       (9153284864653046197, -5.4686551094),
       (227504873216781231, -5.491642952),
       (16875582379069451158, -5.5243682861),
       (7437575085468336610, -5.5344848633),
       (18194338103975822726, -5.6104297638),
       (7148522813498185515, -5.6308684349),
       (1572612192562026184, -5.6501088142),
       (3740602843040177340, -5.654984951),
       (12638816674900267446, -5.7559866905),
       (11667289587015813222, -5.7634425163),
       (12446819118446800910, -5.763589859),
       (6992604926141104606, -5.7726745605000005),
       (9781598966686434415, -5.8237733841),
       (6635067063807956629, -5.8277630806000005),
       (18197037023634208128, -5.8460898399),
       (942632335873952620, -5.9068088531),
       (1655312771067108281, -5.9319047928),
       (7859011591137717335, -5.9366269112),
       (13409319323822384369, -5.9366407394),
       (5059648917813135842, -5.9587073326),
       (2013399242189103424, -5.9926056862),
       (17454115351911680600, -5.9963850975),
       (8504683628951808721, -5.999982357),
       (1696981056005371314, -6.0027008057),
       (7831658034963690409, -6.0101323128),
       (15099054000809333061, -6.014852047),
       (5865838185239622912, -6.0233464241),
       (2199259611705938403, -6.0286955833),
       (3806482680584466996, -6.0386552811),
       (962983613142996970, -6.0506510735),
       (7593739049417968140, -6.0715765953),
       (2160362229054775535, -6.0815982819),
       (11532473245541075862, -6.1288757324),
       (2112642640949226496, -6.1352820396),
       (15947342791229044319, -6.1543049812),
       (16875814820671380748, -6.1809248924),
       (18307573501153647118, -6.1998348236),
       (7976265300568155021, -6.2177276611),
       (16064069575701507746, -6.2300243378),
       (523464648099722843, -6.2554626465),
       (15807309897752499399, -6.2623114586),
       (4678963469726251353, -6.2764940262),
       (10875615029400813363, -6.2785215378),
       (7000492816108906599, -6.3188824654),
       (1248239241591158246, -6.3256053925),
       (16950148841647037698, -6.3496203423),
       (7743033266031195906, -6.3689432144),
       (14653600329166397554, -6.370757103),
       (16764210730586636600, -6.3750867844),
       (8885804376230376864, -6.3782219887),
       (13583488448875926965, -6.3890037537),
       (13055779130471031426, -6.4026918411),
       (12960022596163002503, -6.4542713165),
       (4244585616942201722, -6.4614639282),
       (9698320431655714481, -6.4691567421),
       (16331095434822636218, -6.4967222214),
       (1818273248662495384, -6.5007381439),
       (3876862883474502309, -6.5046372414),
       (10794458019344880855, -6.5122537613),
       (5711639017775284443, -6.5189237595),
       (13398675276606405380, -6.5354423523000005),
       (2661093235354845946, -6.5742750168),
       (1935074700818135162, -6.5843019485),
       (631425121691394544, -6.5864229202),
       (2989924464908128948, -6.5930113792),
       (7494117911267222209, -6.5959591866),
       (2630753287402592467, -6.598200798),
       (1176656782636220709, -6.6438727379),
       (9614445426764226664, -6.6698050499),
       (12517269084653561647, -6.6709165573),
       (9570894245975188254, -6.6731748581),
       (11925638236994514241, -6.6828837395),
       (4759254855483594167, -6.6880803108),
       (5097672513440128799, -6.6887712479),
       (13148361048351484388, -6.6895232201),
       (7597692042947428029, -6.6942048073),
       (17339226045912991082, -6.7029123306),
       (10292920167869855674, -6.7332596779),
       (6878210874361030284, -6.7362723351),
       (11221368173670222813, -6.7372012138),
       (12286903790479710773, -6.7758178711),
       (8004577259940138793, -6.7759652138),
       (1739263527992748485, -6.7830672264),
       (12943039165150086467, -6.7839169502),
       (4115755726172261197, -6.7984867096),
       (14242014708739787450, -6.8333678246),
       (17157488710739566268, -6.8344073296),
       (3899131925553995529, -6.8458080292),
       (5937879255812462177, -6.8675251007),
       (3278561384161438710, -6.8735909462),
       (7063653163634019529, -6.8774709702),
       (17370494668576369452, -6.8873548507999995),
       (6740321247510922449, -6.9015555382),
       (12084876542534825196, -6.9289741516),
       (9548244504980166557, -6.9324288368),
       (5943797630011647483, -6.9337110519),
       (6371478730979445275, -6.9406123161),
       (8685289367999165211, -6.9504799843),
       (5816706412157836887, -6.9580712318),
       (12579384389446384672, -6.9885544777),
       (4525988469032889948, -6.9959039688),
       (478886015463313967, -7.0081033707),
       (12172435438170721471, -7.0121994019),
       (18004243461113809161, -7.0142974854),
       (5456543204961066030, -7.0275449753),
       (15255859468896132977, -7.033305645),
       (7488871353255107396, -7.0531916618),
       (2473243759842082748, -7.063167572),
       (11860158879560853892, -7.0637168884),
       (11104729984170784471, -7.0663957596),
       (411390626470654571, -7.0680251122),
       (13913074996085095135, -7.0712513924),
       (7039397736629347729, -7.0737423897),
       (11195369525898364697, -7.0752868652),
       (14947529218328092544, -7.0789008141),
       (10038440415813069799, -7.0812931061),
       (6873750497785110593, -7.0835962296),
       (10879546028211794123, -7.0846204758),
       (13468287115010965206, -7.1072587967),
       (16680099953739830072, -7.1133351326),
       (6920515201346452032, -7.1136002541),
       (7379188904070621703, -7.1256103516),
       (16318918034475841628, -7.1461701393),
       (959164148857638496, -7.1497254372),
       (3586418546468265269, -7.154941082),
       (2985827712170516640, -7.1573958397),
       (11882120564994168090, -7.1607780457),
       (1692983299745037067, -7.162238121),
       (5224941539530611462, -7.1692552567),
       (16315412628806490806, -7.1789155006),
       (3893465145528745987, -7.1993813515),
       (6789454535283781228, -7.2098126411),
       (6421409113692203669, -7.2235860825),
       (5931147113347055926, -7.2267580032),
       (18024645270525013057, -7.2496404648),
       (11320251846592927908, -7.2533597946),
       (17573686707662795042, -7.2580251694),
       (13428508259213873547, -7.2656517029),
       (3194226484742107227, -7.3133621216),
       (12513610393978129441, -7.3214578629),
       (15180167692696242062, -7.3242683411),
       (5741770584995928333, -7.3425335884),
       (16248400320781648534, -7.3450717926),
       (6090035477591592277, -7.3473567963),
       (16096726548953279178, -7.3524813652),
       (6459564349623679250, -7.3626947403),
       (9492612516460955585, -7.3689875603),
       (3702023516439754181, -7.3726854324),
       (17471638809377599778, -7.3729672432),
       (9720044723474553187, -7.3776130676000005),
       (5381488053361483645, -7.3814644814),
       (14862748245026736845, -7.3854184151),
       (15479733260938818482, -7.3869738579),
       (16574616920585318162, -7.3872127533),
       (8549214374670072303, -7.3950481415),
       (4753564829687343602, -7.3981823921),
       (7136294487848412980, -7.3998990059),
       (1608482186128794349, -7.400947094),
       (15667417291854480293, -7.4025783539),
       (2739543297294151269, -7.4146475792),
       (8881679497796027013, -7.4204545021),
       (17577015140245084783, -7.421028614),
       (11711838292424000352, -7.4336004257),
       (10624292618385541108, -7.4393835068),
       (1039541750886098100, -7.4401707649),
       (11866476999679706272, -7.4409122467),
       (11283501755624150392, -7.4501066208),
       (12342627399458421040, -7.4525637627),
       (9692231336188541085, -7.4563894272),
       (9778055143417507723, -7.4802036285),
       (9067754100579305666, -7.4901075363),
       (6250203919658647129, -7.492556572),
       (8228585124152053988, -7.5022025108),
       (14012806951969610844, -7.5223593712),
       (4812066089261065646, -7.5409207344),
       (17544535479879614370, -7.5429720879),
       (12965068231793614765, -7.5448923111),
       (10515043043501955111, -7.5534424782),
       (1385318218384692368, -7.5647621155),
       (6601561424492272668, -7.5656847954),
       (14889849580704678361, -7.5676813125999995),
       (10951603910464382420, -7.5700330734),
       (16477424308483498569, -7.5742006302),
       (18216413589307435838, -7.5754294395),
       (13296119330568554208, -7.5820116997),
       (5083403373732563023, -7.5863490105),
       (6231102377460051108, -7.5911836624),
       (17831099778462416609, -7.603263855),
       (11640825575873464194, -7.6118631363),
       (15580274710609099813, -7.6118707657),
       (9169342766156091463, -7.6149101257),
       (10066841407251338481, -7.6151719093),
       (1965435164061188486, -7.6297454834),
       (17379251038783395147, -7.6306405067),
       (602994839685422785, -7.6360068321),
       (10321518907502812892, -7.636077404),
       (2646123857127441627, -7.636797905),
       (5533571732986600803, -7.6398329735),
       (4950757572332304006, -7.643693924),
       (16590897233515608007, -7.6453237534),
       (8395131317770283464, -7.6582508087),
       (11532405253426108718, -7.6664738655),
       (3104811030673030468, -7.6687455177),
       (14378475389916013800, -7.6784949303),
       (13268885963146728493, -7.684445858),
       (14917444839815175757, -7.6936311722),
       (5920004935509210957, -7.6940860748),
       (4711265942760212190, -7.6945042610000005),
       (1794436035373472204, -7.7218556404),
       (14800503047316267216, -7.7270765305),
       (3694423386705252764, -7.7342534065),
       (4502205900248518970, -7.737092495),
       (1627781620377393522, -7.743429184),
       (7111508780595485950, -7.7509145737),
       (17461235395181654430, -7.7588152885),
       (5386905846056786656, -7.7594747543),
       (12059514183285037132, -7.7660088539),
       (5307304325359566725, -7.7758569717),
       (9099225972875567996, -7.7782859802),
       (6898525711325499184, -7.7814679146),
       (11792590063656742891, -7.7870750427),
       (9353232606613764737, -7.7883229256),
       (4485934323942657167, -7.7910795212),
       (278066919066513387, -7.7951359749),
       (5791351258821946298, -7.795384407),
       (7270490914741406701, -7.8015065193),
       (18250316222013540736, -7.8165531158),
       (8813345386932560795, -7.81879282),
       (4315396256372657493, -7.83614254),
       (6717419873833042877, -7.8361573219),
       (12647358837591399640, -7.8386888504000005),
       (8848021949395737739, -7.8403964043),
       (4473158105997569131, -7.8414793015),
       (11997309252971546427, -7.844367981),
       (2483095116303079762, -7.8456029892),
       (8336247396359886285, -7.8507881165),
       (12123752991424432577, -7.8543400764),
       (5566782022517605861, -7.8555607796),
       (5691613950422571694, -7.8604364395),
       (8276932932706964455, -7.8672914505),
       (14379783840816760627, -7.8718576431),
       (589070940943333110, -7.8724250793),
       (1703489418272052182, -7.8744120598),
       (6602569202175044994, -7.8768420219),
       (16762307017182994292, -7.8793859482),
       (6785115870927179060, -7.8802924156),
       (15511632813958231649, -7.8807358742),
       (14395066107632849789, -7.8864531517),
       (7936246238499659209, -7.8867249489),
       (5843944760501254262, -7.8903770447),
       (13040105543478938413, -7.8947076797),
       (4927587046501839030, -7.898244381),
       (15726112966383307120, -7.9017462730000005),
       (13695514059466747455, -7.909971714),
       (63172552626595070, -7.9103655815),
       (15185124772021413096, -7.9116392136),
       (6480458294193393462, -7.9239258766),
       (16421957100465448365, -7.9383630753),
       (1651510583525861271, -7.9395446777),
       (7512738811199700769, -7.9547481537),
       (8587113882175654237, -7.9637608528),
       (2906777282977359384, -7.9647846222),
       (7000860569167321224, -7.9658975601),
       (15866718007544400459, -7.9732241631),
       (12380071558262218793, -7.9734907150000005),
       (7050692189315705983, -7.9816207886),
       (10109588199364727116, -7.9821505547000005),
       (200141916689428108, -7.9859886169),
       (2446979777954330933, -7.9891452789),
       (12903434802346126505, -7.9929132462),
       (16619933076130069490, -7.9931659698),
       (7412267946231497360, -7.9960756302),
       (5589923990388768802, -7.9967398643),
       (444920330522528470, -7.9973502159),
       (8663801465970268676, -8.0012636185),
       (7514930894455484064, -8.0016784668),
       (9410232112791000120, -8.0058460236),
       (4063327158281494861, -8.0072240829),
       (14121509715367036122, -8.009806633),
       (18381768081115421630, -8.0101633072),
       (1916734850589852068, -8.0113735199),
       (15871822984945374680, -8.0206260681),
       (3814049101131682695, -8.0327548981),
       (15745985092136828842, -8.0400972366),
       (2090661578966068036, -8.0405340195),
       (17712913731469760764, -8.0440092087),
       (2256871070683278179, -8.0524044037),
       (4303356597303500170, -8.0530700684),
       (8679283378860202508, -8.054775238),
       (16640565335581469180, -8.0642824173),
       (13874798850131827181, -8.0659532547),
       (4454150755681122840, -8.0689468384),
       (3341772144230116515, -8.0690174103),
       (16948554243429412012, -8.0702095032),
       (423185678490233567, -8.0722007751),
       (14681040874823774150, -8.0751676559),
       (18425606103329785088, -8.0822734833),
       (5775260393431306625, -8.0876064301),
       (16743743820210141046, -8.0885105133),
       (6077427682057990751, -8.0910739899),
       (13293160603192985325, -8.096077919),
       (1399273842756378753, -8.097951889),
       (6412587775996070704, -8.1015863419),
       (7508752285157982505, -8.1063861847),
       (8110129090154140942, -8.1068820953),
       (5252949303365547547, -8.1192417145),
       (5379624210385286023, -8.1239480972),
       (2579443659188327298, -8.1244068146),
       (3895058773709925002, -8.1277809143),
       (12346995674149584082, -8.1294565201),
       (9457496526477982497, -8.142950058),
       (11298384275670996895, -8.1475124359),
       (12767647472892411841, -8.1567764282),
       (3979101002134440957, -8.157740593),
       (602335199165703938, -8.1821079254),
       (10779227342117629034, -8.185464859),
       (8328343100126676325, -8.1910867691),
       (13803694918078379268, -8.1915950775),
       (18309932012808971453, -8.1961698532),
       (8811887512194128535, -8.1971387863),
       (2177690308569554941, -8.2001438141),
       (15696715460206213879, -8.2028083801),
       (18432988265768819336, -8.2065982819),
       (16302678419497547123, -8.210515976),
       (3577425109143670181, -8.2272977829),
       (18443948407981750281, -8.227437973),
       (3642769012341782148, -8.2291374207),
       (18281114504200336646, -8.2346172333),
       (4429974322456332988, -8.2362728119),
       (9970931496028849525, -8.236738205),
       (3109722610398367559, -8.2402982712),
       (3240785716591152042, -8.2470216751),
       (14027581762467160941, -8.2486791611),
       (11176473678897442000, -8.2540607452),
       (6572986864102252890, -8.2583770752),
       (7434368892455186804, -8.2593688965),
       (11373740451506967222, -8.259916305499999),
       (5421073421983476317, -8.2642097473),
       (14229572451745258962, -8.2673177719),
       (645224182615914541, -8.2693214417),
       (8369783199685603043, -8.2729701996),
       (11268780503345276587, -8.2856359482),
       (17976686883172633439, -8.2864875793),
       (10609121202681709909, -8.2927818298),
       (5345497848075657444, -8.2933177948),
       (15060127769916968652, -8.296423912),
       (4003250512168697582, -8.2966690063),
       (14249255431398666181, -8.3009338379),
       (16001232513058686804, -8.3037385941),
       (6605652555683495965, -8.3039503098),
       (15549368236163590771, -8.3120317459),
       (4105620495553881905, -8.3160009384),
       (12006852138382633966, -8.3161334991),
       (5415290552571890316, -8.3175649643),
       (15226876150295704304, -8.3242206573),
       (8664790716774201746, -8.3277988434),
       (3439263888874234947, -8.3299341202),
       (13164634093912748321, -8.3384008408),
       (11245257067546591794, -8.3472080231),
       (18193336062778529705, -8.3511428833),
       (15057923854949126052, -8.3557872772),
       (2739140241061867786, -8.3577775955),
       (203487227105936704, -8.3592262268),
       (8253460499044575564, -8.3611059189),
       (15203660437495798636, -8.3630619049),
       (2411557000688341021, -8.364654541),
       (7290638946010101875, -8.3659572601),
       (3636093925232013737, -8.3691596985),
       (16938367552274787525, -8.3715658188),
       (17545852598994811774, -8.3749847412),
       (8706232279129489120, -8.3800992966),
       (15989513710403574752, -8.3827180862),
       (2054481287215635300, -8.3862724304),
       (12090100147684300169, -8.3871011734),
       (16540862642162215401, -8.393746376),
       (14513380027006169650, -8.3955154419),
       (14197355146880858084, -8.3965272903),
       (2718831956170789690, -8.4032459259),
       (3199372179527662625, -8.4037075043),
       (3125235652374451650, -8.4042291641),
       (11091676426636450224, -8.4062004089),
       (12731191880880189974, -8.4109735489),
       (13923566239961886281, -8.4177122116),
       (10460112544927249051, -8.4189796448),
       (12282438651404021516, -8.423324585),
       (4123438333428864925, -8.4265651703),
       (10038222706987769888, -8.4286403656),
       (16884455833306854589, -8.4287815094),
       (11061341230758823191, -8.4344329834),
       (14989697731040454367, -8.4352083206),
       (13033479285224918482, -8.4369449615),
       (2050591882454735094, -8.4374761581),
       (12882971233254586938, -8.4396333694),
       (1322442146463163273, -8.4427757263),
       (10346293177613240481, -8.4429473877),
       (8902621109934631094, -8.4454174042),
       (16009546102277334650, -8.4478626251),
       (1524062747651706878, -8.4528741837),
       (7722715852355611219, -8.4572839737),
       (8419699711262724776, -8.4585008621),
       (10405720708504167118, -8.4602165222),
       (193386613490856276, -8.4650936127),
       (18224404223277189725, -8.4656734467),
       (717880881345064706, -8.4680166245),
       (15201910715624124754, -8.4725141525),
       (99974891130002844, -8.4730138779),

In [10]:
from tqdm.auto import tqdm

spacy_log_probs = []
for word in tqdm(words_df.iterrows()):
    token = nlp(word[1]['Word'])
    if len(token) == 1:
        spacy_log_probs.append({"word_uid": word[1]['WordUID'], "word": word[1]['Word'], "log_prob": token[0].prob, "token_count": len(token)})
    elif len(token) > 1:
        # If the tokenization results in multiple tokens, calculate the average log probability
        sum_log_prob = sum([t.prob for t in token])
        spacy_log_probs.append({"word_uid": word[1]['WordUID'], "word": word[1]['Word'], "log_prob": sum_log_prob, "token_count": len(token)})
    else:
        spacy_log_probs.append({"word_uid": word[1]['WordUID'], "word": word[1]['Word'], "log_prob": None, "token_count": 0})
spacy_log_probs_df = pd.DataFrame(spacy_log_probs)

0it [00:00, ?it/s]

In [29]:
[(k.text, k.prob) for k in nlp("england")]

[('england', -13.3741846085)]

In [12]:
spacy_log_probs_df

       word_uid       word   log_prob  token_count
0             1         if  -5.763590            1
1             2        you  -4.373791            1
2             3       were  -6.673175            1
3             4         to  -3.856022            1
4             5    journey -11.295086            1
...         ...        ...        ...          ...
10134     10135      disks -12.883524            1
10135     10136     stored -11.588490            1
10136     10137    embrace -11.984515            1
10137     10138  coincides -14.459026            1
10138     10139       604m -24.933293            2

[10139 rows x 4 columns]

In [16]:
#use  log_prob to calculate quintiles
spacy_log_probs_df['log_prob'] = spacy_log_probs_df['log_prob'].astype(float)
spacy_log_probs_df['quintiles_a3'] = pd.qcut(spacy_log_probs_df['log_prob'], 5, labels=False)
spacy_log_probs_df['quintiles_a3'] = spacy_log_probs_df['quintiles_a3'].astype(int)

#Join on words_df on word_uid
spacy_log_probs_df = spacy_log_probs_df.merge(words_df, left_on='word_uid', right_on='WordUID', how='left')
spacy_log_probs_df

,word_uid,word,log_prob,token_count,quintiles_a3,WordUID,Word,CharacterLength,LogFrequencies,QuintilesA1,QuintilesA2
0,1,if,-5.763590,1,4,1,if,2,5.256744,4,4
1,2,you,-4.373791,1,4,2,you,3,6.329340,4,4
2,3,were,-6.673175,1,4,3,were,4,4.928421,4,4
3,4,to,-3.856022,1,4,4,to,2,6.063172,4,4
4,5,journey,-11.295086,1,3,5,journey,7,3.007748,3,3
...,...,...,...,...,...,...,...,...,...,...,...
10134,10135,disks,-12.883524,1,2,10135,disks,5,1.913814,2,1
10135,10136,stored,-11.588490,1,3,10136,stored,6,2.230449,2,2
10136,10137,embrace,-11.984515,1,2,10137,embrace,7,2.587711,3,2
10137,10138,coincides,-14.459026,1,1,10138,coincides,9,1.146128,1,0
10138,10139,604m,-24.933293,2,0,10139,604m,4,0.000000,0,-1

In [19]:
spacy_log_probs_df["A1_A2_mismatch"] = spacy_log_probs_df.apply(lambda x: 1 if x['QuintilesA1'] != x['QuintilesA2'] else 0, axis=1)
spacy_log_probs_df["A1_A3_mismatch"] = spacy_log_probs_df.apply(lambda x: 1 if x['QuintilesA1'] != x['quintiles_a3'] else 0, axis=1)
spacy_log_probs_df["A2_A3_mismatch"] = spacy_log_probs_df.apply(lambda x: 1 if x['QuintilesA2'] != x['quintiles_a3'] else 0, axis=1)
spacy_log_probs_df["A1_A2_A3_mismatch"] = spacy_log_probs_df.apply(lambda x: 1 if (x['QuintilesA1'] != x['QuintilesA2']) and (x['QuintilesA1'] != x['quintiles_a3']) and (x['QuintilesA2'] != x['quintiles_a3']) else 0, axis=1)


spacy_log_probs_df

,word_uid,word,log_prob,token_count,quintiles_a3,WordUID,Word,CharacterLength,LogFrequencies,QuintilesA1,QuintilesA2,A1_A2_mismatch,A1_A3_mismatch,A2_A3_mismatch,A1_A2_A3_mismatch
0,1,if,-5.763590,1,4,1,if,2,5.256744,4,4,0,0,0,0
1,2,you,-4.373791,1,4,2,you,3,6.329340,4,4,0,0,0,0
2,3,were,-6.673175,1,4,3,were,4,4.928421,4,4,0,0,0,0
3,4,to,-3.856022,1,4,4,to,2,6.063172,4,4,0,0,0,0
4,5,journey,-11.295086,1,3,5,journey,7,3.007748,3,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10134,10135,disks,-12.883524,1,2,10135,disks,5,1.913814,2,1,1,0,1,0
10135,10136,stored,-11.588490,1,3,10136,stored,6,2.230449,2,2,0,1,1,0
10136,10137,embrace,-11.984515,1,2,10137,embrace,7,2.587711,3,2,1,1,0,0
10137,10138,coincides,-14.459026,1,1,10138,coincides,9,1.146128,1,0,1,0,1,0
10138,10139,604m,-24.933293,2,0,10139,604m,4,0.000000,0,-1,1,0,1,0

In [20]:
subltex_df = pd.read_excel("/home/abishekthamma/PycharmProjects/masters_thesis/ss-llm/nanoGPT/eval/reading_time_analysis/SUBTLEXusExcel2007.xlsx")
subltex_df

,Word,FREQcount,CDcount,FREQlow,Cdlow,SUBTLWF,Lg10WF,SUBTLCD,Lg10CD
0,the,1501908,8388,1339811,8388,29449.176471,6.176644,100.000000,3.923710
1,to,1156570,8383,1138435,8380,22677.843137,6.063172,99.940391,3.923451
2,a,1041179,8382,976941,8380,20415.274510,6.017526,99.928469,3.923399
3,you,2134713,8381,1595028,8376,41857.117647,6.329340,99.916547,3.923348
4,and,682780,8379,515365,8374,13387.843137,5.834281,99.892704,3.923244
...,...,...,...,...,...,...,...,...,...
74281,Zoroastrian,1,1,0,0,0.019608,0.301030,0.011922,0.301030
74282,Zoroastrianism,1,1,0,0,0.019608,0.301030,0.011922,0.301030
74283,zugzwang,1,1,1,1,0.019608,0.301030,0.011922,0.301030
74284,zygotes,1,1,1,1,0.019608,0.301030,0.011922,0.301030
74285,zymurgy,1,1,1,1,0.019608,0.301030,0.011922,0.301030

In [21]:
spacy_log_probs_df["A3_ranks"] = spacy_log_probs_df["log_prob"].rank(method='first', ascending=False)
spacy_log_probs_df["A1_ranks"] = spacy_log_probs_df["LogFrequencies"].rank(method='first', ascending=False)

spacy_log_probs_df

,word_uid,word,log_prob,token_count,quintiles_a3,WordUID,Word,CharacterLength,LogFrequencies,QuintilesA1,QuintilesA2,A1_A2_mismatch,A1_A3_mismatch,A2_A3_mismatch,A1_A2_A3_mismatch,A3_ranks,A1_ranks
0,1,if,-5.763590,1,4,1,if,2,5.256744,4,4,0,0,0,0,30.0,48.0
1,2,you,-4.373791,1,4,2,you,3,6.329340,4,4,0,0,0,0,6.0,1.0
2,3,were,-6.673175,1,4,3,were,4,4.928421,4,4,0,0,0,0,77.0,90.0
3,4,to,-3.856022,1,4,4,to,2,6.063172,4,4,0,0,0,0,2.0,4.0
4,5,journey,-11.295086,1,3,5,journey,7,3.007748,3,3,0,0,0,0,3011.0,2160.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10134,10135,disks,-12.883524,1,2,10135,disks,5,1.913814,2,1,1,0,1,0,5485.0,5855.0
10135,10136,stored,-11.588490,1,3,10136,stored,6,2.230449,2,2,0,1,1,0,3492.0,4776.0
10136,10137,embrace,-11.984515,1,2,10137,embrace,7,2.587711,3,2,1,1,0,0,4142.0,3535.0
10137,10138,coincides,-14.459026,1,1,10138,coincides,9,1.146128,1,0,1,0,1,0,7307.0,7707.0
10138,10139,604m,-24.933293,2,0,10139,604m,4,0.000000,0,-1,1,0,1,0,9814.0,10139.0

In [26]:
for row in spacy_log_probs_df[['WordUID', 'quintiles_a3', 'log_prob']].to_dict(orient='records'):
    c.execute("UPDATE WordDetails SET QuintilesA3 = ?, SpacyTokenProb = ? WHERE WordUID = ?", (row['quintiles_a3'], row['log_prob'], row['WordUID']))
conn.commit()